### ISSUE TITLE
Unable to connect to Axpert king over RS232/TCP

### ISSUE THREAD

**Issue by ttrnkocy** [astraliens/home-assistant-inverter-xpert-king#1] opened 2024-03-15 07:36 UTC
Hi guys,
i am very interrested in your project about connecting Axpert king over RS232/TCP converter to Home Assistant. Currently i read data from the inverter through Node-Red which is working, therefore i believe the converter is set up correctly. Unfortunatelly when i try to add your integration, window for entering converter IP opens, I enter correct values and following error pops-up:

_[%key:common::config_flow::error::unknown%]_

In HA log file it says that error is related with line in the code
_hub.test connection()_

Would you be able to advise?
Thank you.

Tomas

**Comment by astraliens** [comment] 2024-03-15 09:15
Hello, can u plz check if you set also correct tcp port number to connect to inverter. If yes - try temporary disconnect nodered block from inverter (for ex. if inverter connection module support only 1 connection nodered could use it and others can't connect untill it will be released)
if it did not help I'll try to reproduce it in a few hours in dev environment

**Comment by ttrnkocy** [comment] 2024-03-15 09:34
Hi,
port number is correct. Node-red is disabled, RS232/TCP module is restarted. On web status page of the TCP module I see 0 connections, RX/TX packets 0. Once I enter IP and port in HA and click connect, TCP status page is updated with 1 connection and something like 28/56 packets of RX/TX is send and received at every attempt I try to connect from HA. This gives me feeling that comunication between HA and RS232/TCP converter is somehow estabilished, yet HA Xpert integration gives me the error stated above, in log i see:
_Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/inverter_xpert_king/config_flow.py", line 92, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inverter_xpert_king/config_flow.py", line 48, in validate_input
    result = await hub.test_connection()
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Hub' object has no attribute 'test_connection'_

**Comment by astraliens** [comment] 2024-03-15 09:58
Thanks for this log, it looks like I understand what's happening, in a few hours I'll try to reproduce it and fix.

**Comment by astraliens** [comment] 2024-03-15 11:54
@ttrnkocy 
I've updated hub.py.
Can u plz update integration to latest v0.1.3 and try to add inverter once again

**Comment by ttrnkocy** [comment] 2024-03-15 12:29
Magic! It works. Well done and thank you! Will buy you some pizza :-)

![image](https://github.com/astraliens/home-assistant-inverter-xpert-king/assets/163468942/ee62736e-2af2-48d5-ade7-52c735695616)

**Closed as completed** 2024-03-15 12:31 UTC
Labels: bug
